Repository Together42/backend, pull requests merged in 2023-02, with the labels that each got.

#152 modify : rotation GET API 수정
  src/controller/rotation.controller.js
  src/data/rotation.js
  src/routes/rotation.routes.js
Labels: enhancement

#153 modify : rotation GET API query stirng 수정
  src/controller/rotation.controller.js
Labels: enhancement

#154 modify : rotation UPDATE API 수정 및 사서 로테이션 로직 수정
  src/controller/rotation.controller.js
  src/data/rotation.js
  src/utils/rotation.together.js
Labels: bug, enhancement

#158 fix: 사서 로테이션 중복 오류 처리
  src/controller/rotation.controller.js
Labels: bug

#162 issue/73 fix: 비밀번호찾기 기능 수정
  package.json
  src/app.js
  src/controller/auth.controller.js
  src/data/auth.js
  src/routes/auth.routes.js
  yarn.lock
Labels: enhancement
